openapi: 3.0.0
info:
  title: TravelMate Recommendation API
  version: 1.0.0

paths:
  /recommend:
    post:
      summary: Recommend tourist places
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                preferences:
                  type: string
      responses:
        '200':
          description: List of recommended places
